[package]
name = "ist-delegate-election"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.164", features = ["derive"] }
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
