//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod admin;
pub mod election;
pub mod election_vote;
pub mod nomination;
pub mod nomination_log;
pub mod user_degree_override;
pub mod vote_log;
