name: Formatting

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting-backend:
    name: Check Formatting Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo fmt
        run: cargo fmt --check
        working-directory: ./backend

  formatting-frontend:
    name: Check Formatting Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./frontend
      - name: Run prettier
        run: yarn format:check
        working-directory: ./frontend
