name: Formatting

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting-backend:
    name: Check Formatting Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo fmt
        run: cargo fmt --check
        working-directory: ./backend

  formatting-frontend:
    name: Check Formatting Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json
      - name: Install dependencies
        run: npm clean-install
        working-directory: ./frontend
      - name: Run prettier
        run: npm run format:check
        working-directory: ./frontend
